### ISSUE TITLE
how do i pass a user name and password as a secret for a external postgres database?

### ISSUE THREAD

**Issue by weiyentan** [JetBrains/datalore-configs#30]
How do i store an external database connection details as a secret for data lore? I want to store this workflow as a helm chart in gitops and storing my username and paswords is not attractive to me.

**Comment by alexandrvb** [comment]
Hello @weiyentan you can use databaseSecret parameter with existing secret to store the password https://github.com/JetBrains/datalore-configs/blob/2023.3/charts/datalore/values.yaml#L92 

```
databaseSecret:
  create: false
  name: <secret-name>
  key: ROOT_PASSWORD
```
