### ISSUE TITLE
websocket wsdp error

### ISSUE THREAD

**Issue by theartofdevel** [JetBrains/datalore-configs#33]
same issue https://github.com/JetBrains/datalore-configs/issues/25

2024.3 version, setup DATALORE_PUBLIC_URL env and no reaction, same error in browser

**Comment by igRo** [comment]
Hi @theartofdevel, please provide more information on your environment and attach configs (w/o sensitive data ofc).

**Comment by theartofdevel** [comment]
here is my compose
```yaml
services:
  datalore:
    image: jetbrains/datalore-server:2024.3
    networks:
      - datalore-agents-network
      - datalore-backend-network
    environment:
      DATALORE_PUBLIC_URL: "https://my.example.com/"
      DB_PASSWORD: "changeme"
  postgresql:
    image: jetbrains/datalore-postgres:2024.3
    expose: [ "5432" ]
    networks:
      - datalore-backend-network
    environment:
      POSTGRES_PASSWORD: "changeme"

networks:
  datalore-agents-network:
    name: datalore-agents-network
  datalore-backend-network:
    name: datalore-backend-network
```

**Comment by theartofdevel** [comment]
i mean this problem
https://github.com/JetBrains/datalore-configs/issues/25#issuecomment-1319855916

**Comment by theartofdevel** [comment]
i start compose without nginx on 8080 and everything is working. but with nginx nothing works.
how to setup datalore with nginx?

**Comment by igRo** [comment]
`ports` and `expose` sections are missing in your docker-compose.yaml, also there is no mention of nginx service and no nginx configs attached.

**Comment by theartofdevel** [comment]
i have ports section. i have and correct configuration. i did not mention it because it is not a problem with it.

**Comment by theartofdevel** [comment]
```
services:
  datalore:
    image: jetbrains/datalore-server:2024.3
    ports:
      - ":8080:8080"
    networks:
      - datalore-agents-network
      - datalore-backend-network
    environment:
      DATALORE_PUBLIC_URL: "https://my.example.com/"
      DB_PASSWORD: "changeme"
  postgresql:
    image: jetbrains/datalore-postgres:2024.3
    expose: [ "5432" ]
    networks:
      - datalore-backend-network
    environment:
      POSTGRES_PASSWORD: "changeme"
```

in this configuration, if i open in browser 8080 port WITHOUT SSL, WITHOUT nginx - it works perfect.

in frontend console i see the following:
```
00:14:58.899 Starting socket manager: url=ws://my.example.com:8080/wsdp, clientId=<hidden> [datalore.tvm.js:83322:39](http://my.example.com:8080/datalore.tvm.js?v=818)
00:14:59.081 Socket connection opened: ws://my.example.com:8080/wsdp
```

if i want to use nginx as reverse proxy i got an error like in comment https://github.com/JetBrains/datalore-configs/issues/25#issuecomment-1319855916

nginx configuration i took here:
https://www.jetbrains.com/help/datalore/security.html#configure-tls-certificates-for-datalore
